### ISSUE TITLE
Google Sign Up Feature Implementation and Re-Designing the Sign up and Login Form

### ISSUE THREAD

**Issue by ManishBirthlia** [VaibhavArora314/StyleShare#52] opened 2024-05-31 15:59 UTC
Describe the bug
Hello @VaibhavArora314 as we can see If we visit the home page of the website and go to the Sign form then we can see that there is no functionality for signing in with another platform such as Google, LinkedIn, Facebook and Github, etc.

To Reproduce

- Open the home page at https://style-share.vercel.app/app
- Open the Sign in and Sign up form 
- Observe the design and absence of Sign with Google and another platform in the Signup form.
- I want to Introduce this feature

Expected behavior
Implementing Sign up functionality by Google and many other platforms and improving the design of sign-up and Login 
![image](https://github.com/VaibhavArora314/StyleShare/assets/96776615/6a33cebb-3b15-4eed-a37d-ee05f53c84f6)

Screenshots
Before the problem is that there is no feature of Sign in or Login with Google.
![image](https://github.com/VaibhavArora314/StyleShare/assets/96776615/44539ee4-ed09-437f-9b7b-2b668624e3fe)

Hey PA,
I want to work on this issue once you assign me under GSSoC'24 and please assign level 3 to this issue 🙏. Thank You!

**Comment by VaibhavArora314** [comment] 2024-06-01 04:33
Hey @ManishBirthlia , a similar issue #46 already exists

**Comment by ManishBirthlia** [comment] 2024-06-01 05:51
hello @VaibhavArora314 

Actually, I have completed this task but before anything else, I want to know if you are willing to use the Auth feature provided by Kinde ( https://kinde.com/ ) just like Firebase but easier to implement, or if you want to build a complete independent of other's involvement 

Example: By using the Kinde Auth library provided by ( https://kinde.com/ ) it becomes very easy to implement all the entire features like sign-in, Login by password and email ( with email Code verification ), Login by many other platforms like Google, Facebook, GitHub and many more, and they provide everything for free

**Comment by VaibhavArora314** [comment] 2024-06-01 13:11
> hello @VaibhavArora314
> 
> Actually, I have completed this task but before anything else, I want to know if you are willing to use the Auth feature provided by Kinde ( https://kinde.com/ ) just like Firebase but easier to implement, or if you want to build a complete independent of other's involvement
> 
> Example: By using the Kinde Auth library provided by ( https://kinde.com/ ) it becomes very easy to implement all the entire features like sign-in, Login by password and email ( with email Code verification ), Login by many other platforms like Google, Facebook, GitHub and many more, and they provide everything for free

hey I am open to new solutions and kinde looks good also, it is just that the issue is assigned to someone else
if it is not worked upon yet you can work on it.

**Comment by ManishBirthlia** [comment] 2024-06-01 13:34
Okay then i will finish the implementation and let's see how the new features look like 🙌🙂

**Comment by ManishBirthlia** [comment] 2024-06-02 09:47
> hey I am open to new solutions and kinde looks good also, it is just that the issue is assigned to someone else if it is not worked upon yet you can work on it.

@VaibhavArora314 Sorry this took a while. I was getting a handle on the backend and frontend code, plus learning some new stuff like Prisma and Axios. That's why it ended up a bit longer. But I’ve finished the Google login implementation and I'm about to make a merge request, so you can check out all the changes yourself.

**Closed** 2024-06-03 12:22 UTC
